-- 005_chat_reaction_user_unique.sql
-- Reduce UNIQUE on message_reactions to (message_id, user_id):
-- one user may have at most one reaction on a given message.
-- See spec docs/superpowers/specs/2026-04-28-chat-pr8-reactions-design.md §3.

-- 1. Defensive dedup: keep the earliest reaction per (message, user).
--    `min(uuid)` doesn't exist in Postgres, so pick the survivor via
--    DISTINCT ON ordered by created_at, with id as tiebreaker.
delete from message_reactions r
 where r.id not in (
   select distinct on (r2.message_id, r2.user_id) r2.id
     from message_reactions r2
    order by r2.message_id, r2.user_id, r2.created_at, r2.id
 );

-- 2. Drop the old composite UNIQUE generated by the inline
--    `unique (message_id, user_id, emoji)` in 004_chat.sql.
alter table message_reactions
  drop constraint if exists message_reactions_message_id_user_id_emoji_key;

-- 3. Install the new UNIQUE.
alter table message_reactions
  add constraint message_reactions_user_unique unique (message_id, user_id);
