alter table admin_inventory_items
  add column if not exists resource_unit text not null default 'period'
    check (resource_unit in ('period', 'shot', 'distance', 'energy_ms')),
  add column if not exists effect_puck_speed_points int not null default 0,
  add column if not exists effect_stumble_interval_min_ms int not null default 25000
    check (effect_stumble_interval_min_ms >= 0),
  add column if not exists effect_stumble_interval_max_ms int not null default 45000
    check (effect_stumble_interval_max_ms >= effect_stumble_interval_min_ms),
  add column if not exists effect_stumble_duration_min_ms int not null default 250
    check (effect_stumble_duration_min_ms >= 0),
  add column if not exists effect_stumble_duration_max_ms int not null default 400
    check (effect_stumble_duration_max_ms >= effect_stumble_duration_min_ms),
  add column if not exists effect_nutrition_slowdown_ms int not null default 2000
    check (effect_nutrition_slowdown_ms >= 0),
  add column if not exists effect_nutrition_stop_ms int not null default 5000
    check (effect_nutrition_stop_ms >= 0),
  add column if not exists effect_fatigue_delay_ms int not null default 90000
    check (effect_fatigue_delay_ms >= 0),
  add column if not exists effect_fatigue_speed_multiplier numeric(8, 4) not null default 0.88
    check (effect_fatigue_speed_multiplier > 0 and effect_fatigue_speed_multiplier <= 1);

update admin_inventory_items
   set deleted_at = coalesce(deleted_at, now()),
       updated_at = now()
 where deleted_at is null
   and item_kind in ('stick', 'skates', 'nutrition');

insert into admin_inventory_items
  (
    photo_url,
    title,
    description,
    price_rub,
    item_kind,
    rarity,
    currency_price,
    charges_per_purchase,
    duel_period_cost,
    power_score,
    resource_unit,
    effect_puck_speed_points,
    effect_puck_speed_delta,
    effect_stumble_chance,
    effect_stumble_ms,
    effect_stumble_blocks_per_period,
    effect_stumble_interval_min_ms,
    effect_stumble_interval_max_ms,
    effect_stumble_duration_min_ms,
    effect_stumble_duration_max_ms,
    effect_nutrition_slowdown_ms,
    effect_nutrition_stop_ms,
    effect_fatigue_delay_ms,
    effect_fatigue_speed_multiplier
  )
values
  (
    '/inventory/stick-bronze.webp',
    'Ультимейт Ван 1',
    'Комплект клюшек Ультимейт Ван на 1300 бросков. Ускоряет полёт шайбы.',
    0,
    'stick',
    'common',
    1490,
    1300,
    0,
    24,
    'shot',
    10,
    0.10,
    0,
    0,
    0,
    25000,
    45000,
    250,
    400,
    2000,
    5000,
    90000,
    0.88
  ),
  (
    '/inventory/stick-silver.webp',
    'Ультимейт Ван 2',
    'Комплект клюшек Ультимейт Ван на 1950 бросков. Ускоряет полёт шайбы.',
    0,
    'stick',
    'rare',
    2490,
    1950,
    0,
    24,
    'shot',
    10,
    0.10,
    0,
    0,
    0,
    25000,
    45000,
    250,
    400,
    2000,
    5000,
    90000,
    0.88
  ),
  (
    '/inventory/stick-gold.webp',
    'Ультимейт Ван 3',
    'Комплект клюшек Ультимейт Ван на 2500 бросков. Ускоряет полёт шайбы.',
    0,
    'stick',
    'legendary',
    3740,
    2500,
    0,
    24,
    'shot',
    10,
    0.10,
    0,
    0,
    0,
    25000,
    45000,
    250,
    400,
    2000,
    5000,
    90000,
    0.88
  ),
  (
    '/inventory/skates-bronze.webp',
    'Старт',
    'Коньки без спотыкания. Ресурс расходуется от пройденной дистанции.',
    0,
    'skates',
    'common',
    2990,
    1000,
    0,
    24,
    'distance',
    0,
    0,
    0,
    0,
    0,
    25000,
    45000,
    250,
    400,
    2000,
    5000,
    90000,
    0.88
  ),
  (
    '/inventory/nutrition-bronze.webp',
    'Изотоник',
    'Питание на 140 минут активной игры. Помогает держать темп.',
    0,
    'nutrition',
    'common',
    1490,
    8400000,
    0,
    12,
    'energy_ms',
    0,
    0,
    0,
    0,
    0,
    25000,
    45000,
    250,
    400,
    2000,
    5000,
    90000,
    0.88
  ),
  (
    '/inventory/nutrition-silver.webp',
    'Энерго-заряд',
    'Питание на 250 минут активной игры. Помогает держать темп.',
    0,
    'nutrition',
    'rare',
    2490,
    15000000,
    0,
    20,
    'energy_ms',
    0,
    0,
    0,
    0,
    0,
    25000,
    45000,
    250,
    400,
    2000,
    5000,
    90000,
    0.88
  ),
  (
    '/inventory/nutrition-gold.webp',
    'Энерго-комплекс',
    'Питание на 360 минут активной игры. Помогает держать темп.',
    0,
    'nutrition',
    'legendary',
    3490,
    21600000,
    0,
    30,
    'energy_ms',
    0,
    0,
    0,
    0,
    0,
    25000,
    45000,
    250,
    400,
    2000,
    5000,
    90000,
    0.88
  )
on conflict do nothing;
