with achievement_economy_seed (
  id,
  reward_currency,
  reward_stars,
  reward_experience,
  reward_tokens,
  availability,
  future_tag
) as (
  values
    ('ideal-day', 0, 25, 25, 0, 'active', null),
    ('first-goal', 0, 1, 1, 0, 'active', null),
    ('first-daily-game', 0, 2, 2, 0, 'active', null),
    ('first-training', 0, 2, 2, 0, 'active', null),
    ('amateur-ticket', 25000, 250, 250, 5, 'active', null),
    ('pro-ticket', 0, 0, 0, 0, 'future', 'future/pro'),
    ('daily-sniper-streak', 0, 5, 5, 0, 'active', null),
    ('ice-hand', 0, 5, 5, 0, 'active', null),
    ('steady-tempo', 0, 5, 5, 0, 'active', null),
    ('third-period-decides', 0, 5, 5, 0, 'active', null),
    ('final-push', 0, 5, 5, 0, 'active', null),
    ('no-panic', 0, 5, 5, 0, 'active', null),
    ('dry-finish', 0, 5, 5, 0, 'active', null),
    ('keeping-fit', 0, 15, 15, 0, 'active', null),
    ('sniper-week', 0, 20, 20, 0, 'active', null),
    ('sniper-month', 0, 50, 50, 0, 'active', null),
    ('training-monster', 0, 5, 5, 0, 'active', null),
    ('rhythm-control', 0, 5, 5, 0, 'active', null),
    ('cold-start', 0, 3, 3, 0, 'active', null),
    ('no-warmup-needed', 0, 2, 2, 0, 'active', null),
    ('finish-machine', 0, 3, 3, 0, 'active', null),
    ('underdog', 0, 8, 8, 0, 'active', null),
    ('classic-speed', 0, 3, 3, 0, 'active', null),
    ('nervous-finish', 0, 8, 8, 0, 'active', null),
    ('stable-student', 0, 15, 15, 0, 'active', null),
    ('training-before-battle', 0, 5, 5, 0, 'active', null),
    ('dangerous-host', 0, 5, 5, 0, 'active', null),
    ('blowout', 0, 3, 3, 0, 'active', null),
    ('thin-edge', 0, 3, 3, 0, 'active', null),
    ('revenge', 0, 5, 5, 0, 'active', null),
    ('hunter-streak', 0, 10, 10, 0, 'active', null),
    ('clean-win', 0, 5, 5, 0, 'active', null),
    ('dangerous-guest', 0, 8, 8, 0, 'active', null),
    ('no-room-for-error', 0, 3, 3, 0, 'active', null),
    ('wallet', 0, 15, 15, 0, 'active', null),
    ('economical-master', 0, 25, 25, 1, 'active', null),
    ('regular-season-champion', 1500, 50, 50, 3, 'active', null),
    ('regular-season-medalist', 1000, 45, 45, 2, 'active', null),
    ('playoff-semifinal', 750, 50, 50, 1, 'active', null),
    ('playoff-final', 1500, 75, 75, 2, 'active', null),
    ('tournament-cup', 3750, 100, 100, 5, 'active', null),
    ('dark-horse', 0, 25, 25, 0, 'active', null),
    ('death-bracket', 0, 25, 25, 0, 'active', null),
    ('series-comeback', 0, 35, 35, 0, 'active', null),
    ('no-shake', 0, 20, 20, 0, 'active', null),
    ('tournament-streak', 7500, 250, 250, 5, 'active', null),
    ('monthly-top-1', 7500, 100, 100, 3, 'active', null),
    ('monthly-top-3', 3750, 50, 50, 2, 'active', null)
)
update achievements achievement
   set reward_currency = seed.reward_currency,
       reward_stars = seed.reward_stars,
       reward_experience = seed.reward_experience,
       reward_tokens = seed.reward_tokens,
       availability = seed.availability,
       future_tag = seed.future_tag,
       updated_at = now()
  from achievement_economy_seed seed
 where achievement.id = seed.id;
