name: ultimate-hockey

services:
  postgres:
    ports:
      - '${POSTGRES_PORT}:5432'

  redis:
    ports:
      - '${REDIS_PORT}:6379'

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - '3000:3000'

  web:
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - '8080:8080'

  caddy:
    environment:
      APP_DOMAIN: 'http://localhost'
