import { expect,it,vi } from 'vitest';
import { createFightState,DEFAULT_FIGHT_RULES,advanceFight,type FightState } from '@hockey/game-core';
import { fightActionSchema,admitFightCommand } from '../../src/duel/amateur/fight/commands.js';
import type { PoolClient } from 'pg';
vi.mock('../../src/duel/amateur/fight/service.js',()=>({getFight:vi.fn(),queueFightSnapshot:vi.fn(),denyFight:(reason:string)=>{throw Error(reason)}}));
import { getFight } from '../../src/duel/amateur/fight/service.js';
it.each([50,100,200])('allows a150ms defensive response at RTT%i plus20ms one-way jitter',async rtt=>{
 let state:FightState=createFightState(DEFAULT_FIGHT_RULES,0);
 const oneWay=rtt/2+20,compensation=rtt/2;
 vi.mocked(getFight).mockImplementation(async()=>({id:'00000000-0000-4000-8000-000000000001',status:'fighting',engine_state:state,rules:state.rules,compensation_ms:[compensation,compensation]}) as never);
 const query=vi.fn(async(sql:string,args:unknown[])=>{if(sql.startsWith('update amateur_duel_fight set'))state=JSON.parse(args[1] as string);return {rows:[]};});
 const client={query} as unknown as PoolClient;
 const context=(nowMs:number)=>({id:'match',nowMs,participants:[{userId:'a'},{userId:'b'}]}) as never;
 const command=(kind:'attack'|'input',seq:number)=>fightActionSchema.parse({type:'fight:action',fightId:'00000000-0000-4000-8000-000000000001',actionId:`00000000-0000-4000-8000-${String(seq).padStart(12,'0')}`,phaseId:0,seq:1,...(kind==='attack'?{kind,zone:'head'}:{kind,input:{direction:0,crouch:false,guard:true}})});
 const attackSent=1000,attackReceived=attackSent+oneWay,visible=attackReceived+oneWay;
 await admitFightCommand(client,context(attackReceived),'a',command('attack',2));
 const guardPressed=visible+150,guardReceived=guardPressed+oneWay;
 state=advanceFight(state,[],guardReceived-state.rules.deliveryGraceMs).state;
 await admitFightCommand(client,context(guardReceived),'b',command('input',3));
 state=advanceFight(state,[],2000).state;
 expect(state.hp,{rtt,oneWay,visible,guardPressed,guardReceived}).toEqual([5,5]);
 expect(state.actions[0]?.outcome).toBe('blocked');
});
