export const ACHIEVEMENT_CATEGORIES = [
  'daily',
  'training',
  'duel',
  'tournament',
  'shop',
  'rating',
  'level',
] as const;

export type AchievementCategory = (typeof ACHIEVEMENT_CATEGORIES)[number];

export const ACHIEVEMENT_AVAILABILITIES = ['active', 'future', 'hidden'] as const;
export type AchievementAvailability = (typeof ACHIEVEMENT_AVAILABILITIES)[number];

export const ACHIEVEMENT_FUTURE_TAGS = [
  'future/pro',
  'future/tournament',
  'future/monthly_rating',
] as const;

export type AchievementFutureTag = (typeof ACHIEVEMENT_FUTURE_TAGS)[number];

export interface AchievementSeed {
  id: string;
  photoUrl: string;
  title: string;
  description: string;
  requirement: string;
  category: AchievementCategory;
  availability: AchievementAvailability;
  futureTag: AchievementFutureTag | null;
  rewardCurrency: number;
  rewardStars: number;
  rewardExperience: number;
  sortOrder: number;
}

const DEFAULT_REWARD_BY_CATEGORY = {
  daily: { rewardCurrency: 150, rewardStars: 1, rewardExperience: 75 },
  training: { rewardCurrency: 120, rewardStars: 1, rewardExperience: 60 },
  duel: { rewardCurrency: 250, rewardStars: 2, rewardExperience: 120 },
  tournament: { rewardCurrency: 0, rewardStars: 0, rewardExperience: 0 },
  shop: { rewardCurrency: 100, rewardStars: 1, rewardExperience: 50 },
  rating: { rewardCurrency: 0, rewardStars: 0, rewardExperience: 0 },
  level: { rewardCurrency: 300, rewardStars: 3, rewardExperience: 150 },
} satisfies Record<
  AchievementCategory,
  Pick<AchievementSeed, 'rewardCurrency' | 'rewardStars' | 'rewardExperience'>
>;

function reward(category: AchievementCategory) {
  return DEFAULT_REWARD_BY_CATEGORY[category];
}

export const ACHIEVEMENT_SEEDS: AchievementSeed[] = [
  {
    id: 'ideal-day',
    photoUrl: '/achievements/ideal-day.webp',
    title: 'Идеальный день',
    description: 'День, когда каждая шайба нашла сетку.',
    requirement: 'Завершить ежедневную игру 90/90 и тренировку 50/50 в один день.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    rewardCurrency: 500,
    rewardStars: 5,
    rewardExperience: 250,
    sortOrder: 10,
  },
  {
    id: 'first-goal',
    photoUrl: '/achievements/first-goal.webp',
    title: 'Первая шайба',
    description: 'Первый гол всегда самый громкий.',
    requirement: 'Забросить первую шайбу в игре.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    rewardCurrency: 50,
    rewardStars: 1,
    rewardExperience: 25,
    sortOrder: 20,
  },
  {
    id: 'first-daily-game',
    photoUrl: '/achievements/first-daily-game.webp',
    title: 'С почином',
    description: 'Первый полный игровой день позади.',
    requirement: 'Завершить первую ежедневную игру.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    rewardCurrency: 100,
    rewardStars: 1,
    rewardExperience: 50,
    sortOrder: 30,
  },
  {
    id: 'first-training',
    photoUrl: '/achievements/first-training.webp',
    title: 'Начало положено',
    description: 'Тренировочный лед уже знаком.',
    requirement: 'Завершить первую тренировку.',
    category: 'training',
    availability: 'active',
    futureTag: null,
    rewardCurrency: 100,
    rewardStars: 1,
    rewardExperience: 50,
    sortOrder: 40,
  },
  {
    id: 'amateur-ticket',
    photoUrl: '/achievements/amateur-ticket.webp',
    title: 'Билет в Любители',
    description: 'Пора выходить к живым соперникам.',
    requirement: 'Открыть раздел Любители.',
    category: 'level',
    availability: 'active',
    futureTag: null,
    ...reward('level'),
    sortOrder: 50,
  },
  {
    id: 'pro-ticket',
    photoUrl: '/achievements/pro-ticket.webp',
    title: 'Билет в Про',
    description: 'Профессиональная арена ждет своего часа.',
    requirement: 'Открыть раздел Профессионалы.',
    category: 'level',
    availability: 'future',
    futureTag: 'future/pro',
    rewardCurrency: 0,
    rewardStars: 0,
    rewardExperience: 0,
    sortOrder: 60,
  },
  {
    id: 'daily-sniper-streak',
    photoUrl: '/achievements/daily-sniper-streak.webp',
    title: 'Снайперская серия',
    description: 'Серия бросков, где рука не дрогнула.',
    requirement: 'Забить 25 бросков подряд в ежедневной игре.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 70,
  },
  {
    id: 'ice-hand',
    photoUrl: '/achievements/ice-hand.webp',
    title: 'Ледяная рука',
    description: 'Холодная голова и почти безупречная точность.',
    requirement: 'Завершить ежедневную игру с точностью 95%+.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 80,
  },
  {
    id: 'steady-tempo',
    photoUrl: '/achievements/steady-tempo.webp',
    title: 'Ровный темп',
    description: 'Три периода сыграны как по метроному.',
    requirement: 'Во всех 3 периодах ежедневной игры забить одинаково, но не менее 20.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 90,
  },
  {
    id: 'third-period-decides',
    photoUrl: '/achievements/third-period-decides.webp',
    title: 'Третий период решает',
    description: 'Лучший хоккей пришел в нужный момент.',
    requirement: 'Показать лучший результат в 3-м периоде; первые два периода не менее 20.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 100,
  },
  {
    id: 'final-push',
    photoUrl: '/achievements/final-push.webp',
    title: 'Дожим',
    description: 'Концовка периода сыграна без права на ошибку.',
    requirement: 'Забить последние 10 бросков периода подряд. Любая игра кроме тренировки.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 110,
  },
  {
    id: 'no-panic',
    photoUrl: '/achievements/no-panic.webp',
    title: 'Без паники',
    description: 'Плохая серия не сбила темп.',
    requirement: 'После 3 не-голов подряд забить 10 следующих бросков. Любая игра кроме тренировки.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 120,
  },
  {
    id: 'dry-finish',
    photoUrl: '/achievements/dry-finish.webp',
    title: 'Сухая концовка',
    description: 'Финиш дня прошел идеально.',
    requirement: 'Последние 20 бросков ежедневной игры сыграть без промаха.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 130,
  },
  {
    id: 'keeping-fit',
    photoUrl: '/achievements/keeping-fit.webp',
    title: 'Держусь в форме',
    description: 'Неделя стабильного льда.',
    requirement: '7 дней подряд завершать daily с точностью не менее 50% каждый день.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 140,
  },
  {
    id: 'sniper-week',
    photoUrl: '/achievements/sniper-week.webp',
    title: 'Неделя снайпера',
    description: 'Семь полных дней с уверенной точностью.',
    requirement: 'Держать суммарную точность 75%+ за последние 7 завершенных daily.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 150,
  },
  {
    id: 'sniper-month',
    photoUrl: '/achievements/sniper-month.webp',
    title: 'Месяц снайпера',
    description: 'Длинная дистанция для настоящего стрелка.',
    requirement: 'Держать суммарную точность 75%+ за последние 30 завершенных daily.',
    category: 'daily',
    availability: 'active',
    futureTag: null,
    ...reward('daily'),
    sortOrder: 160,
  },
  {
    id: 'training-monster',
    photoUrl: '/achievements/training-monster.webp',
    title: 'Тренировочный монстр',
    description: 'Тренировка прошла почти на максимуме.',
    requirement: 'Забить 45+ из 50 в тренировке.',
    category: 'training',
    availability: 'active',
    futureTag: null,
    ...reward('training'),
    sortOrder: 170,
  },
  {
    id: 'almost-perfect-training',
    photoUrl: '/achievements/almost-perfect-training.webp',
    title: 'Почти идеально',
    description: 'Один бросок отделил от абсолютного дня.',
    requirement: 'Забить 49 из 50 в тренировке.',
    category: 'training',
    availability: 'active',
    futureTag: null,
    ...reward('training'),
    sortOrder: 180,
  },
  {
    id: 'rhythm-control',
    photoUrl: '/achievements/rhythm-control.webp',
    title: 'Контроль ритма',
    description: 'Длинная тренировочная серия без сбоя.',
    requirement: 'В тренировке забить 30 подряд.',
    category: 'training',
    availability: 'active',
    futureTag: null,
    ...reward('training'),
    sortOrder: 190,
  },
  {
    id: 'cold-start',
    photoUrl: '/achievements/cold-start.webp',
    title: 'Холодный старт',
    description: 'Дуэль началась с идеальной серии.',
    requirement: 'Первые 20 бросков в дуэли забить без промаха.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 200,
  },
  {
    id: 'no-warmup-needed',
    photoUrl: '/achievements/no-warmup-needed.webp',
    title: 'Разминка не нужна',
    description: 'Тренировка началась сразу с попаданий.',
    requirement: 'Первые 20 бросков в тренировке забить без промаха.',
    category: 'training',
    availability: 'active',
    futureTag: null,
    ...reward('training'),
    sortOrder: 210,
  },
  {
    id: 'finish-machine',
    photoUrl: '/achievements/finish-machine.webp',
    title: 'Машина на финише',
    description: 'Последний отрезок тренировки прошел идеально.',
    requirement: 'Последние 20 бросков тренировки сыграть на 100%.',
    category: 'training',
    availability: 'active',
    futureTag: null,
    ...reward('training'),
    sortOrder: 220,
  },
  {
    id: 'underdog',
    photoUrl: '/achievements/underdog.webp',
    title: 'Андердог',
    description: 'Победа вопреки разнице в опыте.',
    requirement: 'Победить в дуэли более опытного соперника с опытом не менее 100.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 230,
  },
  {
    id: 'classic-speed',
    photoUrl: '/achievements/classic-speed.webp',
    title: 'Скорость в классике',
    description: 'Быстрый период без потери качества.',
    requirement: 'Отыграть период классической дуэли за 90 секунд с точностью 85%+.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 240,
  },
  {
    id: 'nervous-finish',
    photoUrl: '/achievements/nervous-finish.webp',
    title: 'Нервная концовка',
    description: 'Победа удержана на последней грани.',
    requirement: 'Выиграть в дуэли с разницей в 1 шайбу.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 250,
  },
  {
    id: 'stable-student',
    photoUrl: '/achievements/stable-student.webp',
    title: 'Стабильный ученик',
    description: 'Пять крепких тренировок подряд.',
    requirement: '5 тренировок подряд с результатом 40+ из 50.',
    category: 'training',
    availability: 'active',
    futureTag: null,
    ...reward('training'),
    sortOrder: 260,
  },
  {
    id: 'training-before-battle',
    photoUrl: '/achievements/training-before-battle.webp',
    title: 'Тренировка перед боем',
    description: 'Подготовка сразу принесла победу.',
    requirement: 'Завершить тренировку и затем выиграть следующую дуэль.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 270,
  },
  {
    id: 'dangerous-host',
    photoUrl: '/achievements/dangerous-host.webp',
    title: 'Опасный хозяин',
    description: 'Своя инициатива стала серией побед.',
    requirement: 'Выиграть 3 подряд дуэли, которые начал сам.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 280,
  },
  {
    id: 'blowout',
    photoUrl: '/achievements/blowout.webp',
    title: 'Разгром',
    description: 'Соперник остался далеко позади.',
    requirement: 'Выиграть дуэль с разницей 20+ шайб.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 290,
  },
  {
    id: 'thin-edge',
    photoUrl: '/achievements/thin-edge.webp',
    title: 'На тоненького',
    description: 'Победа с минимальным запасом уверенности.',
    requirement: 'Выиграть дуэль с разницей в 2 шайбы.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 300,
  },
  {
    id: 'revenge',
    photoUrl: '/achievements/revenge.webp',
    title: 'Реванш',
    description: 'Ответ на прошлое поражение пришел сразу.',
    requirement: 'Победить игрока, которому только что проиграл прошлую дуэль.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 310,
  },
  {
    id: 'hunter-streak',
    photoUrl: '/achievements/hunter-streak.webp',
    title: 'Серия охотника',
    description: 'Пять побед подряд в дуэлях.',
    requirement: 'Выиграть 5 дуэлей подряд.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 320,
  },
  {
    id: 'clean-win',
    photoUrl: '/achievements/clean-win.webp',
    title: 'Чистая победа',
    description: 'Классика забрана период за периодом.',
    requirement: 'Выиграть классическую дуэль, победив в каждом периоде.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 330,
  },
  {
    id: 'handled-pressure',
    photoUrl: '/achievements/handled-pressure.webp',
    title: 'Давление выдержано',
    description: 'Соперник закончил раньше, но матч остался за тобой.',
    requirement: 'Выиграть дуэль, где соперник завершил броски раньше тебя.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 340,
  },
  {
    id: 'dangerous-guest',
    photoUrl: '/achievements/dangerous-guest.webp',
    title: 'Опасный гость',
    description: 'Чужой вызов стал твоей серией.',
    requirement: 'Выиграть 3 дуэли подряд, начатые соперниками.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 350,
  },
  {
    id: 'no-room-for-error',
    photoUrl: '/achievements/no-room-for-error.webp',
    title: 'Без права на ошибку',
    description: 'Победа с почти идеальной точностью.',
    requirement: 'Выиграть дуэль, промахнувшись не больше 5 раз.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 360,
  },
  {
    id: 'wallet',
    photoUrl: '/achievements/wallet.webp',
    title: 'Кошелек',
    description: 'Первая реальная покупка в магазине.',
    requirement: 'Совершить первую покупку через оплату.',
    category: 'shop',
    availability: 'active',
    futureTag: null,
    ...reward('shop'),
    sortOrder: 370,
  },
  {
    id: 'economical-master',
    photoUrl: '/achievements/economical-master.webp',
    title: 'Экономный мастер',
    description: 'Победы без дополнительной помощи.',
    requirement: 'Выиграть 10 дуэлей без использования дополнительного инвентаря.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 380,
  },
  {
    id: 'master-arsenal',
    photoUrl: '/achievements/master-arsenal.webp',
    title: 'Арсенал мастера',
    description: 'Каждый слот сработал в победной дуэли.',
    requirement: 'Выиграть дуэль, когда каждый слот инвентаря был задействован.',
    category: 'duel',
    availability: 'active',
    futureTag: null,
    ...reward('duel'),
    sortOrder: 390,
  },
  {
    id: 'playoff-semifinal',
    photoUrl: '/achievements/playoff-semifinal.webp',
    title: 'Турнирный характер',
    description: 'Путь по сетке дошел до решающей стадии.',
    requirement: 'Дойти до полуфинала плей-офф.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 400,
  },
  {
    id: 'playoff-final',
    photoUrl: '/achievements/playoff-final.webp',
    title: 'Финальный лед',
    description: 'Финальная площадка уже близко.',
    requirement: 'Дойти до финала плей-офф.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 410,
  },
  {
    id: 'tournament-cup',
    photoUrl: '/achievements/tournament-cup.webp',
    title: 'Кубок над головой',
    description: 'Турнир завершен чемпионством.',
    requirement: 'Выиграть турнир.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 420,
  },
  {
    id: 'dark-horse',
    photoUrl: '/achievements/dark-horse.webp',
    title: 'Темная лошадка',
    description: 'Более опытный соперник выбит из сетки.',
    requirement: 'Выбить из плей-офф более опытного игрока.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 430,
  },
  {
    id: 'death-bracket',
    photoUrl: '/achievements/death-bracket.webp',
    title: 'Сетка смерти',
    description: 'Три сильных соперника подряд не устояли.',
    requirement: 'Победить 3 соперников подряд, каждого с большим опытом.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 440,
  },
  {
    id: 'series-comeback',
    photoUrl: '/achievements/series-comeback.webp',
    title: 'Мощный камбэк',
    description: 'Серия была перевернута после отставания.',
    requirement: 'Выиграть матч после отставания в серии до нескольких побед.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 450,
  },
  {
    id: 'no-shake',
    photoUrl: '/achievements/no-shake.webp',
    title: 'Без дрожи',
    description: 'Плей-офф сыгран с холодной точностью.',
    requirement: 'В матче плей-офф показать точность 90%+.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 460,
  },
  {
    id: 'tournament-streak',
    photoUrl: '/achievements/tournament-streak.webp',
    title: 'Турнирная серия',
    description: 'Сезон с несколькими кубками.',
    requirement: 'Выиграть 3 турнира за сезон.',
    category: 'tournament',
    availability: 'future',
    futureTag: 'future/tournament',
    ...reward('tournament'),
    sortOrder: 470,
  },
  {
    id: 'monthly-top-1',
    photoUrl: '/achievements/monthly-top-1.webp',
    title: 'Топ 1 месяца',
    description: 'Месяц завершен на вершине рейтинга.',
    requirement: 'Стать победителем рейтинга дуэлей по итогам месяца.',
    category: 'rating',
    availability: 'future',
    futureTag: 'future/monthly_rating',
    ...reward('rating'),
    sortOrder: 480,
  },
  {
    id: 'monthly-top-3',
    photoUrl: '/achievements/monthly-top-3.webp',
    title: 'Топ 3 месяца',
    description: 'Месяц завершен в числе лидеров.',
    requirement: 'Попасть в топ-3 рейтинга дуэлей по итогам месяца.',
    category: 'rating',
    availability: 'future',
    futureTag: 'future/monthly_rating',
    ...reward('rating'),
    sortOrder: 490,
  },
];
