import {
  PERSPECTIVE_COURT_GOALIE_VISUAL_X_SCALE,
  PERSPECTIVE_COURT_GOALIE_VISUAL_Y_OFFSET,
  PERSPECTIVE_COURT_GOAL_VISUAL_OFFSET_X_SCALE,
  PERSPECTIVE_COURT_GOAL_VISUAL_Y_OFFSET,
  PERSPECTIVE_COURT_HITBOX_GOALIE_HEIGHT_SCALE,
  PERSPECTIVE_COURT_HITBOX_GOALIE_INSET,
  PERSPECTIVE_COURT_HITBOX_GOALIE_WIDTH_SCALE,
  PERSPECTIVE_COURT_HITBOX_GOAL_HEIGHT_SCALE,
  PERSPECTIVE_COURT_HITBOX_GOAL_INSET,
  PERSPECTIVE_COURT_HITBOX_GOAL_WIDTH_SCALE,
  PERSPECTIVE_COURT_PUCK_BLADE_OFFSET_X,
  PERSPECTIVE_COURT_PUCK_BLADE_OFFSET_Y,
  PERSPECTIVE_COURT_PUCK_FLIGHT_VISUAL_Y_OFFSET,
  PERSPECTIVE_COURT_VISUAL_Y_OFFSET,
  PERSPECTIVE_COURT_VISUAL_Y_SCALE,
  GOAL_HITBOX_MARGIN,
  GOAL_OPENING,
  resolvePerspectiveCourtShot,
  type GoalieConfig,
  type SessionPhaseOffsets,
  type ShotInput,
  type ShotResult,
  type StickEffects,
} from '@hockey/game-core';

export const TRAINING_NEW_COURT_BACKGROUND = '/sprites/test-court-bg.webp';
export const TRAINING_NEW_COURT_BG_CROP_BOTTOM = '7%';
export const TRAINING_NEW_COURT_VISUAL_Y_SCALE = PERSPECTIVE_COURT_VISUAL_Y_SCALE;
export const TRAINING_NEW_COURT_VISUAL_Y_OFFSET = PERSPECTIVE_COURT_VISUAL_Y_OFFSET;
export const TRAINING_NEW_COURT_GOAL_VISUAL_Y_OFFSET = PERSPECTIVE_COURT_GOAL_VISUAL_Y_OFFSET;
export const TRAINING_NEW_COURT_GOALIE_VISUAL_Y_OFFSET =
  PERSPECTIVE_COURT_GOALIE_VISUAL_Y_OFFSET;
export const TRAINING_NEW_COURT_GOAL_VISUAL_OFFSET_X_SCALE =
  PERSPECTIVE_COURT_GOAL_VISUAL_OFFSET_X_SCALE;
export const TRAINING_NEW_COURT_GOALIE_VISUAL_X_SCALE =
  PERSPECTIVE_COURT_GOALIE_VISUAL_X_SCALE;
export const TRAINING_NEW_COURT_PUCK_BLADE_OFFSET_X = PERSPECTIVE_COURT_PUCK_BLADE_OFFSET_X;
export const TRAINING_NEW_COURT_PUCK_BLADE_OFFSET_Y = PERSPECTIVE_COURT_PUCK_BLADE_OFFSET_Y;
export const TRAINING_NEW_COURT_PUCK_FLIGHT_VISUAL_Y_OFFSET =
  PERSPECTIVE_COURT_PUCK_FLIGHT_VISUAL_Y_OFFSET;
export const TRAINING_NEW_COURT_HITBOX_GOAL_WIDTH_SCALE =
  PERSPECTIVE_COURT_HITBOX_GOAL_WIDTH_SCALE;
export const TRAINING_NEW_COURT_HITBOX_GOAL_HEIGHT_SCALE =
  PERSPECTIVE_COURT_HITBOX_GOAL_HEIGHT_SCALE;
export const TRAINING_NEW_COURT_HITBOX_GOAL_INSET = PERSPECTIVE_COURT_HITBOX_GOAL_INSET;
export const TRAINING_NEW_COURT_HITBOX_GOALIE_WIDTH_SCALE =
  PERSPECTIVE_COURT_HITBOX_GOALIE_WIDTH_SCALE;
export const TRAINING_NEW_COURT_HITBOX_GOALIE_HEIGHT_SCALE =
  PERSPECTIVE_COURT_HITBOX_GOALIE_HEIGHT_SCALE;
export const TRAINING_NEW_COURT_HITBOX_GOALIE_INSET = PERSPECTIVE_COURT_HITBOX_GOALIE_INSET;
export const TRAINING_NEW_COURT_POST_EDGE_DISTANCE = 6;

export function distanceToNewTrainingCourtGoalEdge(
  shooterX: number,
  goalOffsetX: number,
): number {
  const visualGoalOffsetX = goalOffsetX * TRAINING_NEW_COURT_GOAL_VISUAL_OFFSET_X_SCALE;
  const openingCenterX = (GOAL_OPENING.xMin + GOAL_OPENING.xMax) / 2 + visualGoalOffsetX;
  const openingWidth = Math.max(
    0,
    (GOAL_OPENING.xMax - GOAL_HITBOX_MARGIN - (GOAL_OPENING.xMin + GOAL_HITBOX_MARGIN)) *
      TRAINING_NEW_COURT_HITBOX_GOAL_WIDTH_SCALE -
      TRAINING_NEW_COURT_HITBOX_GOAL_INSET * 2,
  );
  const left = openingCenterX - openingWidth / 2;
  const right = openingCenterX + openingWidth / 2;

  if (shooterX < left) return left - shooterX;
  if (shooterX > right) return shooterX - right;
  return 0;
}

export type NewTrainingCourtShotContext = {
  input: ShotInput;
  goalieConfig: GoalieConfig;
  seed: string;
  shotIndex: number;
  stickEffects: StickEffects;
  phaseOffsets: SessionPhaseOffsets;
  shooterX: number;
};

export function resolveNewTrainingCourtShot({
  input,
  goalieConfig,
  seed,
  shotIndex,
  stickEffects,
  phaseOffsets,
}: NewTrainingCourtShotContext): ShotResult {
  return resolvePerspectiveCourtShot(input, goalieConfig, seed, shotIndex, stickEffects, phaseOffsets);
}
