import type { GoalieConfig } from '../goalie/types.js';

// goalAmplitude clamp is 220 (from rink.ts geometry — RINK.width=572,
// GOAL.width=104, MARGIN=14 — минимальный зазор gate-sprite от борта).
const FULL_AMP = 220;

export const GOALIES: readonly GoalieConfig[] = [
  {
    id: 'rookie',
    name: 'Новичок',
    pattern: 'linear',
    hp: 5,
    baseReward: 1,
    firstClearBonus: 20,
    speed: 180,
    amplitude: 1.0,
    frequency: 0.50,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.32,
  },
  {
    id: 'wall',
    name: 'Стена',
    pattern: 'linear',
    hp: 8,
    baseReward: 1,
    firstClearBonus: 40,
    speed: 220,
    amplitude: 1.0,
    frequency: 0.63,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.40,
  },
  {
    id: 'quickfoot',
    name: 'Быстрые ноги',
    pattern: 'linear',
    hp: 12,
    baseReward: 2,
    firstClearBonus: 80,
    speed: 280,
    amplitude: 1.0,
    frequency: 0.88,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.50,
  },
  {
    id: 'octopus',
    name: 'Осьминог',
    pattern: 'sine',
    hp: 15,
    baseReward: 2,
    firstClearBonus: 120,
    speed: 200,
    amplitude: 0.8,
    frequency: 1.0,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.63,
  },
  {
    id: 'dasher',
    name: 'Рывок',
    pattern: 'dash',
    hp: 20,
    baseReward: 3,
    firstClearBonus: 200,
    speed: 0,
    amplitude: 0.9,
    frequency: 1.50,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.75,
  },
  {
    id: 'snowstorm',
    name: 'Метель',
    pattern: 'sine',
    hp: 25,
    baseReward: 3,
    firstClearBonus: 300,
    speed: 0,
    amplitude: 0.95,
    frequency: 1.38,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.88,
  },
  {
    id: 'trickster',
    name: 'Финтарь',
    pattern: 'feint',
    hp: 30,
    baseReward: 4,
    firstClearBonus: 500,
    speed: 0,
    amplitude: 0.9,
    frequency: 1.25,
    goalAmplitude: FULL_AMP,
    goalFrequency: 1.0,
  },
  {
    id: 'iceking',
    name: 'Ледяной Король',
    pattern: 'feint',
    hp: 40,
    baseReward: 5,
    firstClearBonus: 800,
    speed: 0,
    amplitude: 0.95,
    frequency: 1.63,
    goalAmplitude: FULL_AMP,
    goalFrequency: 1.19,
  },
  {
    id: 'shadow',
    name: 'Тень',
    pattern: 'dash',
    hp: 45,
    baseReward: 6,
    firstClearBonus: 1200,
    speed: 0,
    amplitude: 1.0,
    frequency: 2.0,
    goalAmplitude: FULL_AMP,
    goalFrequency: 1.38,
  },
  {
    id: 'legend',
    name: 'Легенда',
    pattern: 'feint',
    hp: 50,
    baseReward: 8,
    firstClearBonus: 2000,
    speed: 0,
    amplitude: 1.0,
    frequency: 2.25,
    goalAmplitude: FULL_AMP,
    goalFrequency: 1.63,
  },
];

const byId = new Map(GOALIES.map((g) => [g.id, g]));

export function getGoalie(id: string): GoalieConfig {
  const cfg = byId.get(id);
  if (!cfg) throw new Error(`Unknown goalie: ${id}`);
  return cfg;
}
