import type { GoalieConfig } from '../goalie/types.js';

// goalAmplitude clamp is 146 (from rink.ts geometry — RINK.width=390, GOAL.width=90).
// Full board-to-board visible from the very first boss — that's the signature mechanic.
const FULL_AMP = 145;

export const GOALIES: readonly GoalieConfig[] = [
  {
    id: 'rookie',
    name: 'Новичок',
    pattern: 'linear',
    hp: 5,
    baseReward: 1,
    firstClearBonus: 20,
    speed: 180,
    amplitude: 1.0,
    frequency: 0.4,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.25,
  },
  {
    id: 'wall',
    name: 'Стена',
    pattern: 'linear',
    hp: 8,
    baseReward: 1,
    firstClearBonus: 40,
    speed: 220,
    amplitude: 1.0,
    frequency: 0.5,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.32,
  },
  {
    id: 'quickfoot',
    name: 'Быстрые ноги',
    pattern: 'linear',
    hp: 12,
    baseReward: 2,
    firstClearBonus: 80,
    speed: 280,
    amplitude: 1.0,
    frequency: 0.7,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.4,
  },
  {
    id: 'octopus',
    name: 'Осьминог',
    pattern: 'sine',
    hp: 15,
    baseReward: 2,
    firstClearBonus: 120,
    speed: 200,
    amplitude: 0.8,
    frequency: 0.8,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.5,
  },
  {
    id: 'dasher',
    name: 'Рывок',
    pattern: 'dash',
    hp: 20,
    baseReward: 3,
    firstClearBonus: 200,
    speed: 0,
    amplitude: 0.9,
    frequency: 1.2,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.6,
  },
  {
    id: 'snowstorm',
    name: 'Метель',
    pattern: 'sine',
    hp: 25,
    baseReward: 3,
    firstClearBonus: 300,
    speed: 0,
    amplitude: 0.95,
    frequency: 1.1,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.7,
  },
  {
    id: 'trickster',
    name: 'Финтарь',
    pattern: 'feint',
    hp: 30,
    baseReward: 4,
    firstClearBonus: 500,
    speed: 0,
    amplitude: 0.9,
    frequency: 1.0,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.8,
  },
  {
    id: 'iceking',
    name: 'Ледяной Король',
    pattern: 'feint',
    hp: 40,
    baseReward: 5,
    firstClearBonus: 800,
    speed: 0,
    amplitude: 0.95,
    frequency: 1.3,
    goalAmplitude: FULL_AMP,
    goalFrequency: 0.95,
  },
  {
    id: 'shadow',
    name: 'Тень',
    pattern: 'dash',
    hp: 45,
    baseReward: 6,
    firstClearBonus: 1200,
    speed: 0,
    amplitude: 1.0,
    frequency: 1.6,
    goalAmplitude: FULL_AMP,
    goalFrequency: 1.1,
  },
  {
    id: 'legend',
    name: 'Легенда',
    pattern: 'feint',
    hp: 50,
    baseReward: 8,
    firstClearBonus: 2000,
    speed: 0,
    amplitude: 1.0,
    frequency: 1.8,
    goalAmplitude: FULL_AMP,
    goalFrequency: 1.3,
  },
];

const byId = new Map(GOALIES.map((g) => [g.id, g]));

export function getGoalie(id: string): GoalieConfig {
  const cfg = byId.get(id);
  if (!cfg) throw new Error(`Unknown goalie: ${id}`);
  return cfg;
}
